### ISSUE TITLE
set_num_teams always sets teams to 5.

### ISSUE THREAD

**Issue by rgammans** [ldnpydojo/ldnpyrobo#1]
Found by inspection , so could I quite probably be mistaken ;-).

Looks like line 16 of d516826502c2253a427193a1ffa64c2b24a1bd61:dojobot.py should read:
   `NUM_TEAMS = n`
not
  `NUM_TEAMS = 5`

**Comment by lordmauve** [comment]
Yes, that was the bug that we hit during the dojo. I fixed it locally but haven't pushed yet.

**Comment by rgammans** [comment]
NP.
 I couldn't make the dojo (so wasn't aware you fixed it ) because it clashes with a writers meeting for a LARP style game we are thinking of running on Discord. Then I saw your bot and felt that looking at some discord API examples would be useful... (but I digress massively)

**Comment by lordmauve** [comment]
Fixed in 38e55f7
